
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123
  jpa: 
    hibernate:
      ddl-auto: update 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  devtools:
    remote:
      restart:
        enabled: true